### ISSUE TITLE
ImportError: No module named _fcdproplus_swig

### ISSUE THREAD

**Issue by ik8ozv** [dl1ksv/gr-fcdproplus#22]
Hi Folks,
please anybody can hwlp me?
when i run the FCDPP Flowgraph i get tis error:

<<< Welcome to GNU Radio Companion 3.7.14.0 >>>

Block paths:
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/lilacsat/Desktop/examples/BY70-2/frontend_by70-2_rx_fcdpp.grc"
>>> Done

Generating: '/home/lilacsat/Desktop/examples/BY70-2/frontend_lilacsat1_rx_rtl.py'

Executing: /usr/bin/python2 -u /home/lilacsat/Desktop/examples/BY70-2/frontend_lilacsat1_rx_rtl.py

Traceback (most recent call last):
  File "/home/lilacsat/Desktop/examples/BY70-2/frontend_lilacsat1_rx_rtl.py", line 30, in <module>
    import fcdproplus
  File "/usr/local/lib/python2.7/dist-packages/fcdproplus/__init__.py", line 45, in <module>
    from fcdproplus_swig import *
  File "/usr/local/lib/python2.7/dist-packages/fcdproplus/fcdproplus_swig.py", line 17, in <module>
    _fcdproplus_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/fcdproplus/fcdproplus_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_fcdproplus_swig')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _fcdproplus_swig

>>> Done

Any help please?
Thanks
73's de Enzo IK8OZV

**Comment by dl1ksv** [comment]
Did you read the dependencies ? Gnuradio 3.8 is required, you use 3.7.
