### ISSUE TITLE
FunCubeDongle for v3.8

### ISSUE THREAD

**Issue by eswnl** [dl1ksv/gr-fcdproplus#26]
Hello,

I have GNU radio 3.8 and Funcube Dongle.

When I install the plugin, I get the blocks to appear. But when I execute the flowchart I get this message:

Traceback (most recent call last):
  File "/home/john/Desktop/none1.py", line 33, in <module>
    import fcdproplus
  File "/usr/lib/python3/dist-packages/fcdproplus/__init__.py", line 45, in <module>
    from .fcdproplus_swig import *
  File "/usr/lib/python3/dist-packages/fcdproplus/fcdproplus_swig.py", line 17, in <module>
    _fcdproplus_swig = swig_import_helper()
  File "/usr/lib/python3/dist-packages/fcdproplus/fcdproplus_swig.py", line 16, in swig_import_helper
    return importlib.import_module('_fcdproplus_swig')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_fcdproplus_swig'

**Comment by dl1ksv** [comment]
Closed, due to missing response.

**Comment by eswnl** [comment]
Sorry for late response. The output I get:

john@john-CF-SX2LETBR:~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fcdproplus
Segmentation fault (core dumped)
john@john-CF-SX2LETBR:~$
